# Generated by Django 4.2.1 on 2023-06-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='fgghhjh', upload_to='pic'),
            preserve_default=False,
        ),
    ]
